### PR TITLE
sync with freebsd master.

### PR DESCRIPTION
**Pull request by fkr**

### CODE REVIEW

**Comment by jordanhubbard** [comment]
Feeker!  You're back! :)

**Comment by fkr** [comment]
yeeeeha :) well, obviously, you should've known that this would be like a honeypot for me...

**Comment by jordanhubbard** [comment]
OK, well, let’s cut out the middleman and just add you to the project eh? :)

**Comment by fkr** [comment]
thanks! Where do you I reach the others? Can you send me some contact infos for the others via mail?

**Comment by jordanhubbard** [comment]
We have a #nextbsd slack channel on the FreeNAS project but we’re just about to fork that off into our own nextbsd team, so stay posted and I’ll get you an invite into the NextBSD slack team!
- Jordan

**Pull request merged**
