### PR TITLE
Next bsd current hardened efi

### PR DESCRIPTION
**Pull request by pkgdemon**
This branch has patches from Eric McCorkle that were submitted to the freebsd-hackers list.  They improve the loader code to allow EFI boot from a ZFS partition which does not work in vanilla FreeBSD yet.  I'm creating a pull request in case you might want them in your repo also.

### CODE REVIEW

**Comment by ghost** [comment]
I believe this should go into the NextBSD-CURRENT-HARDENED branch which appears to have been the original and not NextBSD-CURRENT correct... ??

**Comment by ghost** [comment]
also, please remove all .orig files from the patch and resubmit a pull request.

**Comment by pkgdemon** [comment]
Thanks for pointing out the *.orig.  I did forget to remove those.  I will get that fixed.  Just to clarify would it be preferred that I keep the EFI stuff in it's own branch NextBSD-CURRENT-HARDENED-EFI,  NextBSD-CURRENT-EFI, or should go directly to NextBSD-CURRENT?  I based NextBSD-CURRENT-HARDENED-EFI off of the commits in NextBSD-CURRENT-HARDENED.  But I can create a new branch called NextBSD-CURRENT-EFI as well if that makes more sense.  Let me know.

**Comment by ghost** [comment]
lets leave it in the NextBSD-CURRENT-HARDENED branch, and ill cherry pick it upstream after testing and confirmation it can be upstreamed to NextBSD-CURRENT. As its so far been purely the launchd/MACH works for the moment.

**Comment by pkgdemon** [comment]
Ok.  I'm going to close this pull request.  I'll start fresh, and recommit the patch to NextBSD-CURRENT-HARDENED.  Then I'll run through a pull request again.

**Pull request closed without merging**
